### PR TITLE
Array fix with tests

### PR DESCRIPTION
**Pull request by cag**
@holgerd77 @krzkaczor Continuation of #68 and deals with #69

### CODE REVIEW

**Comment by krzkaczor** [comment]
LGTM but i can verify it test fails BEFORE fix since I can't run tests locally for some weird reason :( I will take a closer look later. 

Btw. @holgerd77 I think coveralls is computing code coverage wrong for ts projects :/ I mentioned it once. It's probably a problem of `nyc`.

**Comment by krzkaczor** [comment]
Btw. nice test @cag ;)

**Comment by holgerd77** [comment]
@krzkaczor Ok, feel free to merge if you are satisfied.

**Comment by krzkaczor** [comment]
@cag @InfiniteStyles  thank you for your contribution! 🎉

**Pull request merged**
