### PR TITLE
Use NestedBufferArray for decode's return type

### PR DESCRIPTION
**Pull request by s1na**
This PR is a breaking change. It changes the signature of `decode` to (see #78 for discussion):

```typescript
export function decode(input: Buffer): Buffer | NestedBufferArray {
```

It moves the streaming version to a new method `decodeStreaming`:

```typescript
export function decodeStreaming(input: Buffer): Decoded {
```

I personally have a hard time figuring out the use-case for `decodeStreaming`?

I think generally working with this `decode` API is hard and given the nature of RLP, we can modify the API to accept some type hints from the user and improve decoding experience. Other RLP libraries have various approaches for this.

- pyrlp uses type hints called sedes which are passed to `decode` function (see [tutorial](https://pyrlp.readthedocs.io/en/latest/tutorial.html#sedes-objects))
- the rust rlp impl keeps the serialized buffer in a struct and offers an [API](https://docs.rs/rlp/0.4.0/rlp/struct.Rlp.html) for getting different parts. E.g. you'd construct an `Rlp` object, and then call `rlp.val_at(1)` to get buffer at index 1, and `rlp.list_at(2)` to get list at index 2

What do others think? @holgerd77 @alcuadrado

### CODE REVIEW

**Comment by ryanio** [comment]
I have rebased this on master.

**Comment by holgerd77** [comment]
@ryanio thanks for picking up some of these older PRs, really appreciated!

**Comment by ryanio** [comment]
@jochem-brouwer @acolytec3 let's see if we can also include this as part of rlp v3 release

**Comment by jochem-brouwer** [comment]
Let's definitely add this one :smile:

**Comment by acolytec3** [comment]
This one is now updated on latest master and I added a test to cover a missing line in the new `decodeStreaming` method.

**Comment by holgerd77** [comment]
Ah, we are working towards RLP v3, sorry I missed that 🙂 with some other comment on #106

**Comment by ryanio** [comment]
have included this as part of https://github.com/ethereumjs/rlp/pull/109/commits/dd122bf2479bf6473d36d1aff3776bed31fe1660

**Pull request closed without merging**
