### PR TITLE
Increase test coverage

### LINKED ISSUE #21: Reach 95%+ code coverage with tests

### PR DESCRIPTION
**Pull request by holgerd77**
Fixes #21 (partly) and #20

### CODE REVIEW

**Comment by axic** [comment]
```
const getTests = exports.getTests = (testType, onFile, fileFilter = /.json$/, skipFn = () => {
```

It doesn't work on 4, I'm fine skipping that.

**Comment by holgerd77** [comment]
That's ok, will push asap.

**Comment by holgerd77** [comment]
@axic Ok, done.

Any insight on the ``getLength`` method? I know understand what it does, I have no imagination what it is used for though. Is this useful and does it make sense to include this in the API later on or should this be removed? I think it should be at least renamed to give more semantics on what it does.

So does it make sense to add tests for this respectively add the checks to existing tests?

**Comment by holgerd77** [comment]
@axic Had a linting error, pushed again.

**Comment by axic** [comment]
I think it tries to extract the size needed to encode the value? Not sure.

**Pull request merged**
