### PR TITLE
added Error when dealing with negativ integers for 

### LINKED ISSUE #71: rlp.encode(-1) should throw an Error.
Currently the `intToBuffer` -function would convert the `-1` to an empty Buffer, since `(-1).toString(16)` creates `-1` and `Buffer.from('-1','hex')` creates an empty Buffer since this is an invalid hex-input. But currently no error is thrown, which simply creates incorrect rlp-representation.

https://github.com/ethereumjs/rlp/blob/master/src/index.ts#L221

### PR DESCRIPTION
**Pull request by simon-jentzsch**
fixed #71

### CODE REVIEW

**Comment by holgerd77** [comment]
Hi Simon, thanks for the PR! There is still a linting error which prevents the tests from passing. You can check with ``npm run lint`` and add a manual temporary ``--fix`` flag in ``package.json`` for fixing.

**Comment by simon-jentzsch** [comment]
thanks, yes fixed it.

**Comment by holgerd77** [comment]
Is this really the intended behavior? What if a signed integer shall be encoded?

**Comment by holgerd77** [comment]
Also, was this a real-world issue you stumbled upon and can you give an example? Can we optimally have a test case for this?

**Comment by chirag-parmar** [comment]
I strongly believe that negative integers must be handled appropriately either by encoding them into 2's complement or by throwing an error. Although, personally, I would prefer that an error is thrown because no specific rule exists for handling negative numbers.

**Comment by simon-jentzsch** [comment]
The problem is simply that this behavior is not defined.
you could convert -1 into
- `0xFF`
- `0xFFFF` 
- `0xFFFFFFFF` 
- `0xFFFFFFFFFFFFFFFF` 
...

All of them would be valid, but at the moment it is converted into `0x` (because Buffer.from does not throw an error), which is definitly invalid.

You asked about an example. We came across this behavior, because we encoded a transacrtionIndex in order to calculate a merkle proof and this happend to be -1, which caused a weird result, since it used `0x` without throwing an error.

**Comment by holgerd77** [comment]
@simon-jentzsch Thanks, really thorough and extensive explanation, great! 👍

**Pull request merged**
